endpoints:
    cors:
        allow-credentials: true
        allowed-headers: '*'
        allowed-methods: '*'
        allowed-origins: '*'
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    instance:
        preferIpAddress: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8072
spring:
    cloud:
        gateway:
            routes: '[{id=organization-service, uri=lb://organization-service, predicates=[Path=/organization/**],
                filters=[RewritePath=/organization/(?<path>.*), /${path}]}, {id=licensing-service,
                uri=lb://licensing-service, predicates=[Path=/license/**], filters=[RewritePath=/license/(?<path>.*),
                /${path}]}]'
        loadbalancer:
            ribbon:
                enabled: false
