eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    instance:
        preferIpAddress: true
example:
    property: I AM THE DEFAULT ORG
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
server:
    port: 8081
spring:
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        platform: postgres
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
