eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    instance:
        preferIpAddress: true
example:
    property: I AM THE DEFAULT ORG
keycloak:
    auth-server-url: http://localhost:8080
    bearer-only: true
    credentials:
        secret: K6s6Fw9jLc5yTBtwjjHaXCVTs5ui3LrF
    realm: spmia-realm
    resource: ostock
    ssl-required: external
    use-resource-role-mappings: false
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
server:
    port: 8081
spring:
    cloud:
        stream:
            bindings:
                output:
                    content-type: application/json
                    destination: orgChangeTopic
            kafka:
                binder:
                    brokers: localhost:9092
                    zkNodes: localhost:9092

    main:
        allow-circular-references: true.
