eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true
example:
  property: I AM THE DEFAULT ORG
keycloak:
  auth-server-url: http://localhost:8080/realms/spmia-realm/protocol/openid-connect/auth
  bearer-only: true
  credentials:
    secret: K6s6Fw9jLc5yTBtwjjHaXCVTs5ui3LrF
  realm: spmia-realm
  resource: ostock
  ssl-required: external
  use-resource-role-mappings: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:

  main:
    allow-circular-references: true.
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
